- name: "workstation configuration"
  hosts: localhost
  become: true
  roles:
  - kewlfft.aur

  tasks:

  # install browsers 
  - name: "install firefox developer edition"
    pacman:
      name: firefox-developer-edition
      state: latest
      update_cache: true

  # install rss reader
  - name: "install feedreader"
    pacman:
      name: feedreader
      state: latest
      update_cache: true

  # website tools
  - name: "install hugo"
    pacman:
      name: hugo
      state: latest
      update_cache: true

  # auth tools
  - name: "install authy"
    become: false
    aur:
      use: yay
      name:
      - authy
      state: latest

  # install and configure aws-cli 2
  - name: "download aws-cli 2 installer"
    unarchive:
      src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      dest: /tmp
      remote_src: true
  - name: "change aws-cli 2 mode"
    file:
      path: /tmp/aws/install
      mode: '755'
  - name: "install aws-cli 2"
    command: "/tmp/aws/install --update"

  # install packer
  - name: "install packer"
    pacman:
      name: packer
      state: latest
      update_cache: true

  # install kubectl
  - name: "install kubectl"
    pacman:
      name: kubectl
      state: latest
      update_cache: true

  # install tfenv
  - name: "clone tfenv"
    git:
      repo: https://github.com/topfreegames/tfenv.git
      dest: /opt/tfenv
  - name: "change tfenv mode"
    file:
      path: /opt/tfenv
      group: luan
      owner: luan
      recurse: yes
  - name: "install tfenv binary"
    file:
      src: /opt/tfenv/bin/tfenv
      dest: /usr/local/bin/tfenv
      state: link
      force: true
  - name: "install terraform binary"
    file:
      src: /opt/tfenv/bin/terraform
      dest: /usr/local/bin/terraform
      state: link
      force: true

  # install kopsenv
  - name: "clone kopsenv"
    git:
      repo: https://github.com/topfreegames/kopsenv.git
      dest: /opt/kopsenv
  - name: "change kopsenv mode"
    file:
      path: /opt/kopsenv
      group: luan
      owner: luan
      recurse: yes
  - name: "install kopsenv binary"
    file:
      src: /opt/kopsenv/bin/kopsenv
      dest: /usr/local/bin/kopsenv
      state: link
      force: true
  - name: "install kops binary"
    file:
      src: /opt/kopsenv/bin/kops
      dest: /usr/local/bin/kops
      state: link
      force: true

  # install helm
  - name: "install helm"
    pacman:
      name: helm
      state: latest
      update_cache: true

  # install vault
  - name: "install vault"
    pacman:
      name: vault
      state: latest
      update_cache: true

  # virtualization
  - name: "install virtualbox"
    pacman:
      name: virtualbox
      state: latest
      update_cache: true

  - name: "install vagrant"
    pacman:
      name: vagrant
      state: latest
      update_cache: true

  # helpers
  - name: "install translate shell"
    pacman:
      name: translate-shell
      state: latest
      update_cache: true

  # terminal
  - name: "install fzf"
    pacman:
      name: fzf
      state: latest
      update_cache: true

  # music
  - name: "install ardour"
    pacman:
      name: ardour
      state: latest
      update_cache: true

  # bluetooth
  - name: "install bluez"
    pacman:
      name: bluez 
      state: latest
      update_cache: true

  - name: "install bluez-utils"
    pacman:
      name: bluez-utils 
      state: latest
      update_cache: true

  - name: "install blueman"
    pacman:
      name: blueman
      state: latest
      update_cache: true

  - name: "install pulseaudio-alsa"
    pacman:
      name: pulseaudio-alsa
      state: latest
      update_cache: true

  - name: "install pulseaudio-bluetooth"
    pacman:
      name: pulseaudio-bluetooth
      state: latest
      update_cache: true


